.TH kylin-scanner 1 "1 May 2020" "The Kylin scanner Project" "Kylin scanner"
.SH NAME
kylin-scanner \- The best GUI frontend for Scanning
.SH SYNOPSIS
.B kylin-scanner
.SH DESCRIPTION
.TP
Kylin Scanner is an interface-friendly scanning software developed with Qt5,
using \fBSANE\fR(1) as its backend.
The software can scan according to the resolution, size and color mode of
the scanning device itself. At the same time, It Increases post-processing of scanned pictures,
including one-click beautification, intelligent correction and text recognition.
Other image processing tips can also be reflected in this software, such as clipping, rotation, etc.
.PP
.SH SEE ALSO
\fBsane\fR(1)
.SH AUTHOR
The author of Kylin scanner is yushuoqi <yushuoqi@kylinos.cn>.

This manual page was written by yushuoqi <yushuoqi@kylinos.cn> for the
Kylin project (but may be used by others).

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 3 or any later
version published by the Free Software Foundation. On Debian systems, the
complete text of the GNU General Public License can be found in
\fB/usr/share/common-licenses/GPL\fR.

.SH BUGS
Please submit bugs to \fBhttps://github.com/ukui/kylin-scanner/issues\fR.
